package totalwavinessofnumbersinrangeii

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class Solution {
    var debuggEnabled = false
    fun logg(s: Any) {
        if (debuggEnabled) println(s)
    }

    var debugfEnabled = false
    fun logf(s: Any) {
        if (debugfEnabled) println(s)
    }

    fun totalWaviness(num1: Long, num2: Long): Long {
        return e(num2) - e(num1 - 1)
    }

    // number of waves for a proper n, no leading 0s
    fun e(num: Long): Long {
        var r = 0L
        var n = num.toString()

        if (n.length < 3) return 0L

        r += f(n)
        var c = n.map { '0' }.toCharArray()
        c[0] = '1'
        r -= f(String(c))

        n = n.drop(1)
        n = String(n.map { '9' }.toCharArray())
        while (n.length > 1) {
            r += f(n)
            c = n.map { '0' }.toCharArray()
            c[0] = '1'
            r -= f(String(c))
            n = n.drop(1)
        }

        return r
    }

    fun naiveF(n: String): Long {
        val l = n.length
        var result = 0L
        for (i in 0..n.toLong()) {
            val nn = i.toString().padStart(l, '0')
            val r = nn
                .zipWithNext(Char::compareTo)
                .zipWithNext()
                .count { (a, b) -> a != 0 && b != 0 && a != b }
            result += r
        }
        return result
    }


    val fm = mutableMapOf<String, Long>()
    // number of waves in [0000]..[n1n2n3n4]
    fun f(n: String): Long {
        if (n.length < 3) return 0L

        if (n in fm) return fm[n]!!

        println("f $n")
        var result = 0L
        val tail = n.drop(1)
        val ninesTail = String(tail.map { '9' }.toCharArray())
        for (first in '0' until n[0]) {
            val g = g(first, ninesTail)
            result += g(first, ninesTail)
            logf("f: ${first}_$ninesTail -> $g")
            result += f(ninesTail)
        }
        val g = g(n[0], tail)
        result += g
        result += f(tail)
        logf("f: ${n[0]}_${tail} -> $g")

        fm[n] = result

        return result
    }


    val fg = mutableMapOf<String, Long>()
    // number of waves generated by adding x in front of all numbers [0000..n1n2n3n4]
    fun g(first: Char, n: String): Long {
        if (n.length < 2) return 0L

        val key ="$first$n"
        if (key in fg) return fg[key]!!

        println("g $first $n")

        var result = 0L

        val tail = n.drop(2)
        val ninesTail = String(tail.map { '9' }.toCharArray())

        for (second in '0' until first) { // \/ wave
            if (second > n[0]) break
            for (third in (second + 1)..'9') {
                if (second == n[0] && third > n[1]) break
                if (second == n[0] && third == n[1]) {
                    result += count(tail)
                    logg("g: $first$second${third}_$tail -> ${count(tail)}")
                } else {
                    result += count(ninesTail)
                    logg("g: $first$second${third}_$ninesTail -> ${count(ninesTail)}")
                }
            }
        }

        for (second in (first + 1)..'9') { // /\ wave
            if (second > n[0]) break
            for (third in '0' until second) {
                if (second == n[0] && third > n[1]) break
                if (second == n[0] && third == n[1]) {
                    result += count(tail)
                    logg("g: $first$second${third}_$ninesTail -> ${count(tail)}")
                } else {
                    result += count(ninesTail)
                    logg("g: $first$second${third}_$ninesTail -> ${count(ninesTail)}")
                }
            }
        }

        fg[key] = result
        return result
    }

    fun count(n: String): Long {
        if (n.isEmpty()) return 1L
        return n.toLong() + 1
    }

}

class SolutionTest {

    private val s = Solution()


    @Test
    fun `test count`() {
        assertEquals(4, s.count("3"))
        assertEquals(22, s.count("21"))
        assertEquals(1, s.count("0"))
        assertEquals(1, s.count("00"))
    }

    @Test
    fun `test g`() {
        assertEquals(13, s.g('2', "15"))
        assertEquals(0, s.g('2', "00"))
        assertEquals(1, s.g('2', "01"))
        assertEquals(11, s.g('2', "020"))
    }

    @Test
    fun `test f`() {
        println(s.naiveF("121"))
        println(s.naiveF("2123"))
        assertEquals(s.naiveF("2124"), s.f("2124"))
        assertEquals(s.naiveF("1000"), s.f("1000"))
        println(s.f("1000") to s.naiveF("1000"))
        assertEquals(s.naiveF("81032"), s.f("81032"))
    }

    @Test
    fun `test e`() {
//        assertEquals(11, s.e(121))
        assertEquals(1776, s.e(2124))
        assertEquals(13056, s.e(11242))

        // 2124 -> 1776
//        println(s.f("2124"))
//        println(s.f("1000"))
//        println(s.f("999"))
//        println(s.f("100"))
//        println(s.f("000"))
//        assertEquals(2124, s.f("2124") - s.f("1000") + s.f("999"))
//        assertEquals(2124, s.e(2124))
    }

    @Test
    fun test2() {
        assertEquals(3, s.totalWaviness(120, 130))
        assertEquals(3, s.totalWaviness(198, 202))
        assertEquals(3, s.totalWaviness(198, 202))
        assertEquals(3, s.totalWaviness(198, 202))
        assertEquals(5614, s.totalWaviness(123, 5328))
    }
}
